---
# This assigns a PR to its author
addAssignees: author

reviewers:
  # The default reviewers
  defaults:
    - maintainers

  groups:
    maintainers:
      - milindtrivedisonos
      - trivedi-mi
      - joshi-pa

files:
  '**/*':
    - maintainers


options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - wip
    - DO NOT MERGE
  enable_group_assignment: false
  number_of_reviewers: 1
