area:
  - 'bug'
  - 'found'
  - 'important'
  - 'not found'
  - 'not merging'

# Labels that can be applied to PRs with the /kind command
kind:
  - 'failing'
  - 'cleanup'

labelapplyaa:
  - .github/**/*
automerge:
  - .github/**/*
