name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled,edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "feature,fix,maintenance"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['feature','fix','maintenance']"
        BANNED_LABELS: "hold"
        BANNED_LABELS_DESCRIPTION: "Cannot merge a pr when hold label is present"
