#
on: pull_request_review
name: Label approved pull requests
jobs:
  labelWhenApproved:
    name: Label when approved
    if: contains( github.event.pull_request.labels.*.name, 'In progress')
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: abinoda/label-when-approved-action@v1.0.7
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        ADD_LABEL: "approved"
        REMOVE_LABEL: "In%20progress"
