on: pull_request_review
name: Label approved pull requests
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@v1.0.7
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        ADD_LABEL: "approved"
        REMOVE_LABEL: "In%20progress"
